name = "filcdn-dashboard"
main = "index.js" 
compatibility_date = "2025-09-10"

[[d1_databases]]
binding = "DB"
database_name = "filcdn-dashboard-test"
database_id = "d667e64d-d744-4226-a60a-68aaafb0fec5"
